---
framework: jest
modifiers:
  - type: jest
postMerge:
  pattern:
  strategy:
    threshold: <5|100s>
    type: <commit|time>
preMerge:
  pattern:
stability:
  consecutive_runs: 5
preRun:
  - yarn build:js
postRun:
  - node --version
version: 2.0
